# Generated by Django 4.0 on 2024-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('linea', models.IntegerField()),
                ('orden', models.CharField(max_length=50)),
                ('motivo_t3', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
                ('devolucion', models.BooleanField(default=False)),
                ('archivo', models.FileField(upload_to='archivos_excel/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
