# Generated by Django 4.0 on 2024-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_archivos', '0002_alter_archivoexcel_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoexcel',
            name='fecha_de_cita',
            field=models.DateField(null=True),
        ),
    ]
