# Generated by Django 4.0 on 2024-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_archivos', '0003_archivoexcel_fecha_de_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoexcel',
            name='linea',
            field=models.IntegerField(null=True),
        ),
    ]
